version: '3'
services:
  web-api:
    build: .
    # VULNERABILITY: Mapping to 0.0.0.0 makes the app public to the entire network
    ports:
      - "80:80"
    # VULNERABILITY: Privileged mode gives the container root access to the host kernel
    privileged: true
    depends_on:
      - broker

  broker:
    image: redis:latest # VULNERABILITY: Using 'latest' tag (Mutable/Unpredictable)
    # VULNERABILITY: Exposing the database port to the outside world
    ports:
      - "6379:6379"
    command: redis-server --requirepass admin_password_123